### ISSUE TITLE
Input ignored if you tap the hand

### ISSUE THREAD

**Issue by Eeems** [bkirwi/folly#1]
When trying to quit, it will ask if you want to exit, after replying "y" it will not quit.

**Comment by bkirwi** [comment]
Hrm... as in, the game will resume as before instead of bailing out to the main menu?

If so - that's probably a HWR bug, though a nasty one! If you can attach the `ink.log` file in the `encrusted` dir I should be able to confirm. You could also try entering `yes` at the prompt, which IIRC should also work and is more likely to be recognized.

**Comment by Eeems** [comment]
![2021-07-14T214100 748](https://user-images.githubusercontent.com/1176979/125696865-541cf29f-dc71-4677-947b-c3ad04ee6da9.png)
[ink.log](https://github.com/bkirwi/encrusted/files/6819071/ink.log)

**Comment by bkirwi** [comment]
fascinating... not a handwriting recognition bug after all; it's being correctly recognized in the log.

i'll have a look - thanks for the debugging info.

**Comment by bkirwi** [comment]
just noticed that little ink spot in the left margin... are you interacting directly with the little hand on the left in any way? (using it as a submit button, for example?)

**Comment by Eeems** [comment]
I tapped it with the pen before remembering I had to use my finger to tap it. The same thing happens if I don't do that though.

**Comment by bkirwi** [comment]
you shouldn't actually have to tap it at all... it should interpret as soon as you move the pen away from the screen. tapping it submits a blank input. (which is a feature i added to handle the "press enter to continue" style prompts that expect a blank line.)

tested this morning, and it looks like if you tap immediately after writing it will ignore the input. i suspect that's what you're running into... and whether or not your input was recognized depends on whether you hit the (very small) tap target on the hand. 

iirc the game only responds `[I beg your pardon]` when a blank line has been submitted, so this looks like this happened on the first line in the screenshot as well.

if you're up to test again with all lowercase inputs, and without interacting with the hand at all, i'd be curious to see if that behaves better for you. no pressure of course!

either way, ignoring already-provided input when the hand is tapped on is bad behaviour... i'll fix that. 

i'll also look at adding some tutorial content to the app. (eg. the fact that we expect lowercase input is only documented in the readme, where folks won't necessarily be looking for it, and writing in uppercase will just silently give you worse results.)

**Comment by Eeems** [comment]
This does appear to be what is happening. If I move my pen away from the screen and wait long enough it does quit properly.

That tutorial would be a great idea. Maybe include a default level that's just the tutorial and have it guide you through how to use the application, as well as show off some standard commands. That or include a cheat sheet that can be pulled up.

**Comment by bkirwi** [comment]
ah, excellent, thanks for confirming!

and yeah, a playable tutorial level would be neat. i'll see what i can do.

**Comment by bkirwi** [comment]
marking this closed, since there's a bit of a tutorial now and the bug should be long gone... thanks again for reporting.
